kafka:
    brokers: ["app-redpanda-0:9092"]
    schemaRegistry:
        enabled: true
        urls: ["http://app-redpanda-0:8081"]
redpanda:
    adminApi:
        enabled: true
        urls: ["http://app-redpanda-0:9644"]
