framework:
    messenger:
        default_bus: none.bus
        buses:
            none.bus:
                default_middleware:
                    allow_no_handlers: true
            command.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true
                middleware:
                    - dispatch_after_current_bus
            
            query.bus:
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true
                middleware:
                    - dispatch_after_current_bus
            immediate_event.bus:
                default_middleware: 
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true
        failure_transport: failed
        transports:
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            kafka_wikipedia:
                dsn: '%env(KAFKA_EVENTS_MESSENGER_TRANSPORT_DSN)%'
                options:
                    json_serialization:
                        enabled: true
                    consumer:
                        routing:
                            -   name: 'wikipedia.change.occurred'
                                class: 'App\Modules\Wikipedia\Domain\WikipediaChangedOccurred'
                    topics: [ 'evt.wikipedia.changes' ]
            kafka_events:
                dsn: '%env(KAFKA_EVENTS_MESSENGER_TRANSPORT_DSN)%'
                options:
                    json_serialization:
                        enabled: true
                    consumer:
                        routing:
                            -   name: 'test_event'
                                class: 'App\Modules\UI\Cli\TestMessage'
                    topics: [ 'test_topic' ]
        routing:
            'App\Modules\UI\Cli\TestMessage': kafka_events
            'App\Modules\Wikipedia\Domain\WikipediaChangedOccurred': kafka_wikipedia
