# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                location: '%kernel.project_dir%/public/%uploads_dir_name%'
        private_uploads_adapter:
            local:
                location: '%kernel.project_dir%/files'
    filesystems:
        private_uploads:
            adapter: private_uploads_adapter
            alias: League\Flysystem\Filesystem
        public_uploads:
            adapter: public_uploads_adapter
            mount: public_uploads
