vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        agent_documents:
            upload_destination: '%kernel.project_dir%/files/agent_documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        agent_avatars: # nombre del mapping
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
